version: '3'
services:
  web:
    build: .
    container_name: DEV
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html/
      - ./server/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./server/apache2.conf:/etc/apache2/apache2.conf
      - ./server/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - database

  database:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DBNAME}
      MYSQL_ROOT_PASSWORD: ${ROOTPWD}
      MYSQL_USER: ${USER}
    volumes:
      - ./db_data:/var/lib/mysql
      - ./www/jclm_database.sql:/docker-entrypoint-initdb.d/0_init.sql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      - database
    ports:
      - 8888:80
    environment:
      - PMA_ARBITRARY=1
